# Autogenerated with SMOP version 0.23
# main.py why.m -o why.py
from __future__ import division
from random import randrange
import os

def why():
	randi = randrange(1, 10)
	if 1 == randi:
		a=special_case()
	else:
		if [2] == randi or 3 == randi or [4] == randi:
			a=phrase()
		else:
			a=sentence()
	return a
	
def special_case():
	randi = randrange(1, 12)
	if 1 == randi:
		a='why not?'
	else:
		if 2 == randi:
			a="don't ask!"
		else:
			if 3 == randi:
				a="it's your karma."
			else:
				if 4 == randi:
					a='stupid question!'
				else:
					if 5 == randi:
						a='how should I know?'
					else:
						if 6 == randi:
							a='can you rephrase that?'
						else:
							if 7 == randi:
								a='it should be obvious.'
							else:
								if 8 == randi:
									a='the devil made me do it.'
								else:
									if 9 == randi:
										a='the computer did it.'
									else:
										if 10 == randi:
											a='the customer is always right.'
										else:
											if 11 == randi:
												a='in the beginning, God created the heavens and the earth...'
											else:
												if 12 == randi:
													a="don't you have something better to do?"
	return a
def phrase():
	randi = randrange(1, 3)
	if 1 == randi:
		a='for the ' + nouned_verb() + ' ' + prepositional_phrase() + '.'
	else:
		if 2 == randi:
			a='to ' + present_verb() + ' ' + object_() + '.'
		else:
			if 3 == randi:
				a='because ' + sentence()
	return a
def preposition():
	randi = randrange(1,2)
	if 1 == randi:
		a='of'
	else:
		if 2 == randi:
			a='from'
	return a
def prepositional_phrase():
	randi = randrange(1, 3)
	if 1 == randi:
		a=preposition() + ' ' + article() + ' ' + noun_phrase()
	else:
		if 2 == randi:
			a=preposition() + ' ' + proper_noun()
		else:
			if 3 == randi:
				a=preposition() + ' ' + accusative_pronoun()
	return a
def sentence():
	a=subject() + ' ' + predicate() + '.'
	return a
def subject():
	randi = randrange(1, 4)
	if 1 == randi:
		a=proper_noun()
	else:
		if 2 == randi:
			a=nominative_pronoun()
		else:
			a=article() + ' ' + noun_phrase()
	return a
def proper_noun():
	randi = randrange(1, 12)
	if 1 == randi:
		a='Cleve'
	else:
		if 2 == randi:
			a='Jack'
		else:
			if 3 == randi:
				a='Bill'
			else:
				if 4 == randi:
					a='Joe'
				else:
					if 5 == randi:
						a='Pete'
					else:
						if 6 == randi:
							a='Loren'
						else:
							if 7 == randi:
								a='Damian'
							else:
								if 8 == randi:
									a='Barney'
								else:
									if 9 == randi:
										a='Nausheen'
									else:
										if 10 == randi:
											a='Mary Ann'
										else:
											if 11 == randi:
												a='Penny'
											else:
												if 12 == randi:
													a='Mara'
	return a
def noun_phrase():
	randi = randrange(1, 4)
	if 1 == randi:
		a=noun()
	else:
		if 2 == randi:
			a=adjective_phrase() + ' ' + noun_phrase()
		else:
			a=adjective_phrase() + ' ' + noun()
	return a
def noun():
	randi = randrange(1, 5)
	if 1 == randi:
		a='mathematician'
	else:
		if 2 == randi:
			a='programmer'
		else:
			if 3 == randi:
				a='system manager'
			else:
				if 4 == randi:
					a='engineer'
				else:
					if 5 == randi:
						a='hamster'
					else:
						if 6 == randi:
							a='kid'
	return a
def nominative_pronoun():
	randi = randrange(1, 5)
	if 1 == randi:
		a='I'
	else:
		if 2 == randi:
			a='you'
		else:
			if 3 == randi:
				a='he'
			else:
				if 4 == randi:
					a='she'
				else:
					if 5 == randi:
						a='they'
	return a
def accusative_pronoun():
	randi = randrange(1, 4)
	if 1 == randi:
		a='me'
	else:
		if 2 == randi:
			a='all'
		else:
			if 3 == randi:
				a='her'
			else:
				if 4 == randi:
					a='him'
	return a
def nouned_verb():
	randi = randrange(1, 2)
	if 1 == randi:
		a='love'
	else:
		if 2 == randi:
			a='approval'
	return a
def adjective_phrase():
	randi = randrange(1, 6)
	if [1] == randi or [2] == randi or [3] == randi:
		a=adjective()
	elif [4] == randi or [5] == randi:
		a=adjective_phrase() + ' and ' + adjective_phrase()
	else:
		a=adverb() + ' ' + adjective()
	return a
def adverb():
	randi = randrange(1, 3)
	if 1 == randi:
		a='very'
	else:
		if 2 == randi:
			a='not very'
		else:
			if 3 == randi:
				a='not excessively'
	return a
def adjective():
	randi = randrange(1, 7)
	if 1 == randi:
		a='tall'
	else:
		if 2 == randi:
			a='bald'
		else:
			if 3 == randi:
				a='young'
			else:
				if 4 == randi:
					a='smart'
				else:
					if 5 == randi:
						a='rich'
					else:
						if 6 == randi:
							a='terrified'
						else:
							if 7 == randi:
								a='good'
	return a
def article():
	randi = randrange(1, 3)
	if 1 == randi:
		a='the'
	else:
		if 2 == randi:
			a='some'
		else:
			if 3 == randi:
				a='a'
	return a
def predicate():
	randi = randrange(1, 3)
	if 1 == randi:
		a=transitive_verb() + ' ' + object_()
	else:
		a=intransitive_verb()
	return a
def present_verb():
	randi = randrange(1, 3)
	if 1 == randi:
		a='fool'
	else:
		if 2 == randi:
			a='please'
		else:
			if 3 == randi:
				a='satisfy'
	return a
def transitive_verb():
	randi = randrange(1, 10)
	if 1 == randi:
		a='threatened'
	else:
		if 2 == randi:
			a='told'
		else:
			if 3 == randi:
				a='asked'
			else:
				if 4 == randi:
					a='helped'
				else:
					a='obeyed'
	return a
def intransitive_verb():
	randi = randrange(1, 6)
	if 1 == randi:
		a='insisted on it'
	else:
		if 2 == randi:
			a='suggested it'
		else:
			if 3 == randi:
				a='told me to'
			else:
				if 4 == randi:
					a='wanted it'
				else:
					if 5 == randi:
						a='knew it was a good idea'
					else:
						if 6 == randi:
							a='wanted it that way'
	return a
def object_():
	randi = randrange(1, 10)
	if 1 == randi:
		a=accusative_pronoun()
	else:
		a=article() + ' ' + noun_phrase()
	return a

if __name__ == "__main__":
	why();